version: 'Build {build}'
image: Visual Studio 2019
skip_branch_with_pr: true
  
build_script:
  - ps: dotnet restore
  - ps: dotnet build --no-restore -c Release
  - ps: |
        $env:COMPlus_EnableAVX2 = 1
        $env:COMPlus_EnableSSE41 = 1
        $env:COMPlus_EnableSSE2 = 1
        Write-Host "Test Environment: Normal" -ForegroundColor "Cyan"
        dotnet test --no-restore /p:SkipBuildVersioning=true

        $env:COMPlus_EnableAVX2 = 1
        $env:COMPlus_EnableSSE41 = 1
        $env:COMPlus_EnableSSE2 = 1
        Write-Host "Test Environment: AVX2 Disabled" -ForegroundColor "Cyan"
        dotnet test --no-restore --framework netcoreapp3.1 /p:SkipBuildVersioning=true
        
        $env:COMPlus_EnableAVX2 = 1
        $env:COMPlus_EnableSSE41 = 1
        $env:COMPlus_EnableSSE2 = 1
        Write-Host "Test Environment: SSE41 Disabled" -ForegroundColor "Cyan"
        dotnet test --no-restore --framework netcoreapp3.1 /p:SkipBuildVersioning=true
        
        $env:COMPlus_EnableAVX2 = 1
        $env:COMPlus_EnableSSE41 = 1
        $env:COMPlus_EnableSSE2 = 1
        Write-Host "Test Environment: SSE2 Disabled" -ForegroundColor "Cyan"
        dotnet test --no-restore --framework netcoreapp3.1 /p:SkipBuildVersioning=true
  - ps: dotnet pack --no-build -c Release /p:PackageOutputPath=build-artifacts
  
test: false
artifacts:
  - path: '.\build-artifacts\*'

deploy:
  - provider: NuGet
    artifact: /.*nupkg/
    api_key:
      secure: ZvZldMVYtRaJ47p+5VHv9Ria4qLQ0TAqaNI4OI2fufqdnMBYqV4wzq8S7zIMqKMg
    on:
      APPVEYOR_REPO_TAG: true
  
  - provider: NuGet
    server: https://nuget.pkg.github.com/Turnerj/index.json
    artifact: /.*\.nupkg/
    skip_symbols: true
    username: Turnerj
    api_key:
      secure: XnTMWCpraeRGwQ/HGCQIneJDAIIsF7MypVnaShycKC95P3+IA0MF+qXV16c8/5jg
    on:
      APPVEYOR_REPO_TAG: true

  - provider: GitHub
    artifact: /.*nupkg/
    draft: true
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'TODO'
    auth_token:
      secure: 8WGv8noklaCJAQEBpcs+VShk/Hql5zbyx0VPhMvzUw0RcG7rAd2KxKIh4gazXlBi
    on:
      APPVEYOR_REPO_TAG: true
